import type { ShortlistResult, VendorResult } from "./gemini";

export function generateMarkdownReport(
  need: string,
  requirements: string[],
  weights: Record<string, number>,
  excludedVendors: string[],
  result: ShortlistResult,
): string {
  const timestamp = new Date(result.generatedAt).toLocaleString();

  let md = `# Vendor Shortlist Report\n\n`;
  md += `**Generated:** ${timestamp}\n\n`;
  md += `## Need\n\n${need}\n\n`;

  md += `## Requirements\n\n`;
  requirements.forEach((req) => {
    const w = weights[req] ?? 5;
    md += `- ${req} *(weight: ${w}/10)*\n`;
  });

  if (excludedVendors.length > 0) {
    md += `\n## Excluded Vendors\n\n${excludedVendors.join(", ")}\n`;
  }

  md += `\n## Comparison Table\n\n`;
  md += `| Vendor | Score | Price Range | Key Matches | Risks |\n`;
  md += `|--------|-------|-------------|-------------|-------|\n`;

  result.vendors.forEach((v) => {
    const matched = v.matchedFeatures.filter((f) => f.matched).length;
    const total = v.matchedFeatures.length;
    const topRisk = v.risks[0] || "None";
    md += `| **${v.name}** | ${v.score}/100 | ${v.priceRange} | ${matched}/${total} requirements | ${topRisk} |\n`;
  });

  md += `\n## Vendor Details\n\n`;

  result.vendors.forEach((v: VendorResult, i: number) => {
    md += `### ${i + 1}. ${v.name} — Score: ${v.score}/100\n\n`;
    md += `**Website:** [${v.website}](${v.website})\n\n`;
    md += `**Price Range:** ${v.priceRange}\n\n`;
    md += `**Summary:** ${v.summary}\n\n`;

    md += `**Requirements Match:**\n\n`;
    v.matchedFeatures.forEach((f) => {
      const icon = f.matched ? "[PASS]" : "[FAIL]";
      md += `- ${icon} **${f.requirement}** — ${f.detail}\n`;
    });

    md += `\n**Risks & Limitations:**\n\n`;
    v.risks.forEach((r) => {
      md += `- [RISK] ${r}\n`;
    });

    md += `\n**Evidence Links:**\n\n`;
    v.evidenceLinks.forEach((e) => {
      md += `- [${e.title}](${e.url})\n  > ${e.snippet}\n\n`;
    });

    md += `---\n\n`;
  });

  md += `*Generated by VendorDiscovery — Powered by Groq Llama 3.3 70B*\n`;
  return md;
}
